### PR TITLE
Report coverage for rewired modules

### PR DESCRIPTION
**Pull request by lexun**
Hello, I've taken a shot at https://github.com/stephanos/rewire/issues/10. The implementation is an adaptation of the mimic solution linked in the issue. I'm gradually adopting rewire in a real project using this branch and everything seems to be working fine so far.

### CODE REVIEW

**Comment by stephanos** [comment]
@lexun sorry for the late response; I'll try to take a look soon!

PS: I've noticed the Travis CI step is failing, could you look into that?

**Comment by lexun** [comment]
Now I'm sorry for the late response 😅

I added workarounds for the previous CI issues, and now have some new things to sort through. I'm hoping I'll be able to cave out some time to wrap it up next Friday.

**Comment by lexun** [comment]
So I believe the Elixir 1.14 issue is fixed. The last problem is an intermittent failure where sometimes not all function calls are accounted for in the coverage data. It appears to be that sometimes callbacks registered to `ExUnit.after_suite/1` aren't executed by the time `Rewire.TestCover` performs its analysis, but I'm not certain why yet.

**Comment by lexun** [comment]
@stephanos Alright, I think this is finally ready for your review. Thanks for your patience! 🙂

**Comment by stephanos** [comment]
@lexun wow, amazing work! After I left my last company, I don't have an Elixir code base to test this on anymore. But I'm okay with merging - and fixing forward if anything goes wrong.

**Pull request merged**
